notesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: notes
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: notesId
        AttributeType: S
    KeySchema:
      - AttributeName: notesId
        KeyType: HASH

cognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: devNotesUserPool

cognitoUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    UserPoolId: !Ref cognitoUserPool
    ClientName: web

cognitoUserPoolDomain:
  Type: AWS::Cognito::UserPoolDomain
  Properties:
    UserPoolId: !Ref cognitoUserPool
    Domain: mynotescd

userPoolIdParam:
  Type: AWS::SSM::Parameter
  Properties:
    Type: String
    Name: /notes/dev/userpoolId
    Value: !GetAtt cognitoUserPool.Arn
