notesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: notes-${self.provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: notesId
        AttributeType: S
    KeySchema:
      - AttributeName: notesId
        KeyType: HASH

cognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: devNotesUserPool

cognitoUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    UserPoolId: !Ref cognitoUserPool
    ClientName: web
    AllowedOAuthFlows:
      - implicit
    CallbackURLs:
      - http://localhost:3000
    AllowedOAuthFlowsUserPoolClient: true
    AllowedOAuthScopes:
      - phone
      - email
      - openid
      - profile
    SupportedIdentityProviders:
      - COGNITO

cognitoUserPoolDomain:
  Type: AWS::Cognito::UserPoolDomain
  Properties:
    UserPoolId: !Ref cognitoUserPool
    Domain: mynotescd-${self.provider.stage}

userPoolIdParam:
  Type: AWS::SSM::Parameter
  Properties:
    Type: String
    Name: /notes/${self.provider.stage}/userpoolId
    Value: !GetAtt cognitoUserPool.Arn
