notesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: notes-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: notesId
        AttributeType: S
    KeySchema:
      - AttributeName: notesId
        KeyType: HASH

cognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: devNotesUserPool

cognitoUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    UserPoolId: !Ref cognitoUserPool
    ClientName: web
    AllowedOAuthFlows:
      - implicit
    CallbackURLs:
      - http://localhost:3000
    AllowedOAuthFlowsUserPoolClient: true
    AllowedOAuthScopes:
      - phone
      - email
      - openid
      - profile
    SupportedIdentityProviders:
      - COGNITO

cognitoUserPoolDomain:
  Type: AWS::Cognito::UserPoolDomain
  Properties:
    UserPoolId: !Ref cognitoUserPool
    Domain: mynotescd-${self:provider.stage}

userPoolIdParam:
  Type: AWS::SSM::Parameter
  Properties:
    Type: String
    Name: /notes/${self:provider.stage}/userpoolId
    Value: !GetAtt cognitoUserPool.Arn

notesApplicationWebAcl:
  Type: AWS::WAFv2::WebACL
  Properties:
    Scope: REGIONAL
    Name: notesApplicationWebAcl
    Rules:
      - Name: commonManagedRules
        Priority: 1
        Statement:
          ManagedRuleGroupStatement:
            VendorName: AWS
            Name: AWSManagedRulesCommonRuleSet
            RuleActionOverrides:
              - Name: managedRuleOverride
                ActionToUse:
                  Block:
                    CustomResponse:
                      ResponseCode: 405
                      ResponseHeaders:
                        - Name: x-cf-reject
                          Value: Rejected
        VisibilityConfig:
          CloudWatchMetricsEnabled: true
          MetricName: myWafRuleLogs
          SampledRequestsEnabled: true
    DefaultAction:
      Allow: {}
    VisibilityConfig:
      CloudWatchMetricsEnabled: true
      MetricName: myWafLogs
      SampledRequestsEnabled: true

notesApiCachePolicy:
  Type: AWS::CloudFront::CachePolicy
  Properties:
    CachePolicyConfig:
      DefaultTTL: 300
      MaxTTL: 31536000
      MinTTL: 60
      Name: NotesApiCachePolicy
      ParametersInCacheKeyAndForwardedToOrigin:
        CookiesConfig:
          CookieBehavior: none
        EnableAcceptEncodingBrotli: true
        EnableAcceptEncodingGzip: true
        HeadersConfig:
          HeaderBehavior: whitelist
          Headers:
            - Authorization
        QueryStringsConfig:
          QueryStringBehavior: none

cloudFrontDistribution:
  Type: AWS::CloudFront::Distribution
  Properties:
    DistributionConfig:
      Enabled: true
      DefaultCacheBehavior:
        TargetOriginId: notesApiOrigin
        CachePolicyId: !Ref notesApiCachePolicy
        ViewerProtocolPolicy: https-only
      CacheBehaviors:
        - PathPattern: /dev/*
          TargetOriginId: notesApiOrigin
          CachePolicyId: !Ref notesApiCachePolicy
          ViewerProtocolPolicy: https-only
      WebACLId: !GetAtt notesApplicationWebAcl.Id
      Origins:
        - Id: notesApiOrigin
          DomainName: !Join
            - "."
            - - !Ref ApiGatewayRestApi
              - "execute-api"
              - ${self:provider.region}
              - "amazonaws.com"
          CustomOriginConfig:
            OriginProtocolPolicy: https-only