service: notes
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  stage: dev

functions:
  createNote:
    handler: handler.createNote
    events:
      - http:
          method: post
          path: notes
  updateNote:
    handler: handler.updateNote
    events:
      - http:
          method: put
          path: notes/{id}
